### ISSUE TITLE
可以添加对wstring的支持么

### ISSUE THREAD

**Issue by XSANElimos** [dujingning/inicpp#1]

**Comment by dujingning** [comment]
添加了对 std::wstring 的值写入、读取支持，请查看是否符合预期：

调用示例代码如下（其他见example）：
`
	// std::wstring support
	std::locale::global(std::locale("")); // support wide string output

	std::wstring helloWorld_value = L"你好，世界"; // translate as : hello,world
	_ini.modify("other", "desc", helloWorld_value, "this test for std::wstring. comment only if any.");

	std::wstring wstr = _ini["other"].toWString("desc");
	std::wcerr << "to wstring:\tother.desc= " << wstr << std::endl;
`
