### ISSUE TITLE
如果ini文件不存在，库似乎不会有错误提示

### ISSUE THREAD

**Issue by kevinswat** [dujingning/inicpp#3]
感谢dujingning提供这样一个纯head文件的ini库。经过试用，发现正常读取功能运行良好。但若预设路径的ini文件不存在或存在错误时，程序并不会输出错误提示，且在数据缺失时尝试转换为int类型会默认输出0（这可能取决于作者的定义）。这种情况下，如果开发者没有注意到并且没有进行错误处理，可能会在使用该库的程序中引发一些预料之外的错误。

Thank you to dujingning for providing such a pure header file for the ini library. Upon testing, it was found that the normal reading functionality works well. However, when the ini file specified in the preset path does not exist or contains errors, the program does not output an error message. Additionally, when data is missing, attempting to convert it to an int type defaults to outputting 0 (which may depend on the author's definition). In such cases, if developers do not notice this and do not perform error handling, it may lead to unexpected errors in programs using this library.

**Comment by dujingning** [comment]
如果对输出有严格的存在性判断，参见`README.md`文档的`Usage`子项的第5、6项或者自定义异常检查函数（下文会给出示例代码）

## 一、已提供判断函数
优先使用接口处理，程序根据需求做出反应。示例代码见`README.md`
```
Ⅲ、Usage
* 5.isKeyExists()
* 6.isSectionExists()、getSectionsList()
```
## 二、抛异常的 key 检查示例
个人对C++异常的使用持谨慎态度，如需必须要异常中断程序，你可以自定异常检查函数对所有必要参数进行检查，这样的话异常抛出是用户可控的。

这里提供一个示例demo：strict_example.cpp
```cpp
#include "inicpp.hpp"
#include <iostream>
#include <stdexcept>
#include <vector>


void CheckFunction(inicpp::section&& sec,const std::vector<std::string>& keys)
{
    for( const auto& key: keys)
    {
        if ( !sec.isKeyExist( key ) )
        {
            throw std::logic_error("`Config of Section/Key: " + sec.name() + "->" + key + " Not Exists!`");
        }
    }
}


void readConfig()
{
    inicpp::IniManager _ini("config.ini");

    // check keys from section 'rtsp'
    CheckFunction(_ini["rtsp"], {"port", "ip", "id"} );
}


int main()
{
    try{

        readConfig();

    } catch (const std::exception& e) {
        std::cerr << "Read Config File with Error : " << e.what() << std::endl;
    }

    return 0;
}
```
编译运行：
```bash
[jn@jn example]$ g++ -I../ -std=c++11 strict_example.cpp -o strict_iniExample
[jn@jn example]$ ./strict_iniExample
Read Config File with Error : `Config of Section/Key: rtsp->id Not Exists!`
[jn@jn example]$
```
如果不对异常处理，程序将会异常退出，同样带有自定义的提示：
```bash
[jn@jn example]$ ./strict_iniExample
terminate called after throwing an instance of 'std::logic_error'
  what():  `Config of Section/Key: rtsp->id Not Exists!`
Aborted (core dumped)
[jn@jn example]$
```

## 三、思考
无论库抛出异常还是提供错误码，都会增加使用者的负担，上述两种方案希望对你有所帮助。

另外，你也可以尝试为`key-value`提供默认参数，这样即使配置文件异常，程序也可以正常运行，一些开源中间件也是这么实践的。

**Comment by dujingning** [comment]
The exception example will be added to `README.md` and included as an example in the future.
